### ISSUE TITLE
Unable To Build Module

### ISSUE THREAD

**Issue by mykec** [mwelchuk/usbtv#5]
Hello!  I am attempting to make my EasyCAP function under Linux Mint 18.2 using x86 64-bit.  Have you a solution for getting beyond this roadblock?

$ dkms build -m usbtv -v 1.0

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=4.4.0-53-generic KVERSION=4.4.0-53-generic KERNELDIR=/lib/modules/4.4.0-53-generic/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.4.0-53-generic (x86_64)
Consult /var/lib/dkms/usbtv/1.0/build/make.log for more information.
sillygoose ~ # cat /var/lib/dkms/usbtv/1.0/build/make.log 
DKMS make.log for usbtv-1.0 for kernel 4.4.0-53-generic (x86_64)
Tue Oct 31 11:09:23 EDT 2017
make -C /lib/modules/4.4.0-53-generic/build M=/var/lib/dkms/usbtv/1.0/build
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-53-generic'
  LD      /var/lib/dkms/usbtv/1.0/build/built-in.o
  CC [M]  /var/lib/dkms/usbtv/1.0/build/usbtv.o
/var/lib/dkms/usbtv/1.0/build/usbtv.c:227:9: error: conflicting types for ‘vb2_fop_write’
 ssize_t vb2_fop_write(struct file *file, char __user *buf,
         ^
In file included from include/media/videobuf2-vmalloc.h:16:0,
                 from /var/lib/dkms/usbtv/1.0/build/usbtv.c:41:
include/media/videobuf2-v4l2.h:134:9: note: previous declaration of ‘vb2_fop_write’ was here
 ssize_t vb2_fop_write(struct file *file, const char __user *buf,
         ^
/var/lib/dkms/usbtv/1.0/build/usbtv.c: In function ‘usbtv_image_chunk’:
/var/lib/dkms/usbtv/1.0/build/usbtv.c:617:10: error: ‘struct vb2_buffer’ has no member named ‘v4l2_buf’
   buf->vb.v4l2_buf.field = V4L2_FIELD_INTERLACED;
          ^
/var/lib/dkms/usbtv/1.0/build/usbtv.c:618:10: error: ‘struct vb2_buffer’ has no member named ‘v4l2_buf’
   buf->vb.v4l2_buf.sequence = usbtv->sequence++;
          ^
/var/lib/dkms/usbtv/1.0/build/usbtv.c:619:30: error: ‘struct vb2_buffer’ has no member named ‘v4l2_buf’
   v4l2_get_timestamp(&buf->vb.v4l2_buf.timestamp);
                              ^
/var/lib/dkms/usbtv/1.0/build/usbtv.c: At top level:
/var/lib/dkms/usbtv/1.0/build/usbtv.c:946:17: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .queue_setup = usbtv_queue_setup,
                 ^
/var/lib/dkms/usbtv/1.0/build/usbtv.c:946:17: note: (near initialization for ‘usbtv_vb2_ops.queue_setup’)
/var/lib/dkms/usbtv/1.0/build/usbtv.c:949:20: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
  .stop_streaming = usbtv_stop_streaming,
                    ^
/var/lib/dkms/usbtv/1.0/build/usbtv.c:949:20: note: (near initialization for ‘usbtv_vb2_ops.stop_streaming’)
/var/lib/dkms/usbtv/1.0/build/usbtv.c: In function ‘usbtv_probe’:
/var/lib/dkms/usbtv/1.0/build/usbtv.c:1029:10: error: ‘V4L2_FL_USE_FH_PRIO’ undeclared (first use in this function)
  set_bit(V4L2_FL_USE_FH_PRIO, &usbtv->vdev.flags);
          ^
/var/lib/dkms/usbtv/1.0/build/usbtv.c:1029:10: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:264: recipe for target '/var/lib/dkms/usbtv/1.0/build/usbtv.o' failed
make[2]: *** [/var/lib/dkms/usbtv/1.0/build/usbtv.o] Error 1
Makefile:1418: recipe for target '_module_/var/lib/dkms/usbtv/1.0/build' failed
make[1]: *** [_module_/var/lib/dkms/usbtv/1.0/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-53-generic'
Makefile:2: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by mwelchuk** [comment]
Unless it's been disabled for some reason, the driver that you have in Linux Mint 18 (from the v4.4 kernel) is far newer than that provided in this repo (which was a back port of the driver from v3.14 to v3.2). This out of tree driver is going to give you nothing more than you already have in Linux Mint 18 an possibly far less.

**Comment by mykec** [comment]
Very well.  Thanks.  I have successfully installed the firmware into my EasyCAP device but I'm still unable to use it for lack of its appearance as an available device on my system.  (i.e. no /dev/video0, etc.)  I assumed this was due to the lack of a driver - which led me here.

**Comment by mwelchuk** [comment]
As I understand it, there are a whole variety of different devices marketed as "EasyCAP", so it may well be that you have on of the devices not supported by this driver.
