### ISSUE TITLE
make build fails

### ISSUE THREAD

**Issue by AdrienLemaire** [mwelchuk/usbtv#2]
Hi,

I'm trying to build your driver on arch linux. When running the **dkms build** command, I get the following error:

```
$ sudo dkms build -m usbtv -v 1.0                ⏎

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=3.16.4-1-ARCH KVERSION=3.16.4-1-ARCH
KERNELDIR=/lib/modules/3.16.4-1-ARCH/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 3.16.4-1-ARCH (x86_64)
Consult /var/lib/dkms/usbtv/1.0/build/make.log for more information.
```

and here is the make.log:

```
DKMS make.log for usbtv-1.0 for kernel 3.16.4-1-ARCH (x86_64)
Tue Oct 21 11:09:37 JST 2014
make -C /lib/modules/3.16.4-1-ARCH/build M=/var/lib/dkms/usbtv/1.0/build
make[1]: Entering directory '/usr/lib/modules/3.16.4-1-ARCH/build'
  LD      /var/lib/dkms/usbtv/1.0/build/built-in.o
  CC [M]  /var/lib/dkms/usbtv/1.0/build/usbtv.o
/var/lib/dkms/usbtv/1.0/build/usbtv.c:227:9: error: conflicting types for ‘vb2_fop_write’
 ssize_t vb2_fop_write(struct file *file, char __user *buf,
         ^
In file included from /var/lib/dkms/usbtv/1.0/build/usbtv.c:40:0:
include/media/videobuf2-core.h:613:9: note: previous declaration of ‘vb2_fop_write’ was here
 ssize_t vb2_fop_write(struct file *file, const char __user *buf,
         ^
/var/lib/dkms/usbtv/1.0/build/usbtv.c:949:2: warning: initialization from incompatible pointer type
  .stop_streaming = usbtv_stop_streaming,
  ^
/var/lib/dkms/usbtv/1.0/build/usbtv.c:949:2: warning: (near initialization for ‘usbtv_vb2_ops.stop_streaming’)
scripts/Makefile.build:263: recipe for target '/var/lib/dkms/usbtv/1.0/build/usbtv.o' failed
make[2]: *** [/var/lib/dkms/usbtv/1.0/build/usbtv.o] Error 1
Makefile:1333: recipe for target '_module_/var/lib/dkms/usbtv/1.0/build' failed
make[1]: *** [_module_/var/lib/dkms/usbtv/1.0/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/3.16.4-1-ARCH/build'
Makefile:2: recipe for target 'default' failed
make: *** [default] Error 2
```

This seems to be an upstream problem. Do you think you can fix it?

Cordially

**Comment by mwelchuk** [comment]
Hi Adrien,

This driver was backported from 3.14 to the 3.2 kernel in Ubuntu 12.04. The 3.16 kernel you have in Arch Linux should already have a slightly newer version of the driver. You shouldn't need to install this one.

Martyn

**Comment by AdrienLemaire** [comment]
Correct, I was able to use do my stuff with the default usbtv module, sorry ^^ Closing this issue, thanks for your answer!
